### ISSUE TITLE
ERROR:  duplicate key value violates unique constraint "o_test_1"

### ISSUE THREAD

**Issue by Tanyaevm** [orioledb/orioledb#95] opened 2022-10-10 11:11 UTC
specs/test.spec:

Error for postgres:
```
ERROR:  could not serialize access due to read/write dependencies among transactions
```

Error with orioledb:
```
ERROR:  duplicate key value violates unique constraint "o_test_1"
```

```sql
setup
{
	CREATE EXTENSION IF NOT EXISTS orioledb;

	CREATE TABLE o_test_1(
		val_1 integer UNIQUE,
    	val_2 text
	)USING orioledb;

	CREATE OR REPLACE FUNCTION func_1(k integer, v text) 
		RETURNS void
		AS $$
		INSERT INTO o_test_1 (val_1, val_2) 
		SELECT k, v WHERE NOT EXISTS 
		(SELECT val_1 FROM o_test_1 WHERE val_1 = k);
	$$ LANGUAGE SQL;
}

teardown
{
  DROP FUNCTION func_1(integer, text);
  DROP TABLE o_test_1;
}

session s1
setup { BEGIN ISOLATION LEVEL SERIALIZABLE; }
step "select_1" { SELECT func_1(1, '1'); }
step "commit_1" { COMMIT; }

session s2
setup { BEGIN ISOLATION LEVEL SERIALIZABLE; }
step "select_2" { SELECT func_1(1, '2'); }
step "commit_2" { COMMIT; }

permutation "select_1" "select_2" "commit_1" "commit_2"
```

Run as:
```
make USE_PGXS=1 isolationcheck ISOLATIONCHECKS="test"
```

**Comment by akorotkov** [comment] 2022-12-29 06:16
Duplicate of #131

**Closed by akorotkov** 2022-12-29 06:16 UTC
Labels: bug
