### ISSUE TITLE
Optimizer statistics difference

### ISSUE THREAD

**Issue by ioxgrey** [orioledb/orioledb#20] opened 2022-03-23 11:50 UTC
After pgbench initialization estimated and actual rows are differs by two order of magnitude.
```
postgres=# select n_live_tup from pg_stat_user_tables where relname = 'pgbench_accounts';
 n_live_tup 
------------
  100003298
(1 row)

postgres=# explain (analyze, buffers) select count(1) from pgbench_accounts;
                                                              QUERY PLAN                                                               
---------------------------------------------------------------------------------------------------------------------------------------
 Aggregate  (cost=164157.55..164157.56 rows=1 width=8) (actual time=30772.449..30772.451 rows=1 loops=1)
   ->  Seq Scan on pgbench_accounts  (cost=0.00..150086.64 rows=5628364 width=0) (actual time=0.141..24405.699 rows=100000000 loops=1)
 Planning:
   Buffers: shared hit=23 read=2
 Planning Time: 0.458 ms
 Execution Time: 30772.624 ms
(6 rows)

postgres=# 
```

**Comment by akorotkov** [comment] 2022-03-26 19:20
Could you please recheck this with f49091b9d9?

**Comment by akorotkov** [comment] 2022-03-26 20:30
What was the scale factor and `orioledb.main_buffers`?  Also, did you restart PostgreSQL after pgbench initialization?

**Comment by akorotkov** [comment] 2022-03-27 03:48
Please, recheck 65fe3558c3.

**Comment by ioxgrey** [comment] 2022-03-27 06:17
```orioledb.main_buffers = '64GB'
```
I do not restart PostgreSQL during this test

**Comment by akorotkov** [comment] 2022-03-27 07:15
Thank you. Could you recheck the issue on 65fe355?

**Comment by ioxgrey** [comment] 2022-03-27 08:38
On 65fe355 vacuum looks good, but optimizer still missing rows num.
```
postgres=# select n_live_tup from pg_stat_user_tables where relname = 'pgbench_accounts';
 n_live_tup 
------------
   99999964
(1 row)

postgres=# explain (analyze, buffers) select count(1) from pgbench_accounts;
                                                              QUERY PLAN                                 
                              
---------------------------------------------------------------------------------------------------------
------------------------------
 Aggregate  (cost=164155.21..164155.22 rows=1 width=8) (actual time=25309.116..25309.118 rows=1 loops=1)
   ->  Seq Scan on pgbench_accounts  (cost=0.00..150084.77 rows=5628177 width=0) (actual time=0.028..2036
8.969 rows=100000000 loops=1)
 Planning:
   Buffers: shared hit=23 read=2
 Planning Time: 0.179 ms
 Execution Time: 25309.170 ms
(6 rows)

postgres=#vacuum  verbose analyze  pgbench_accounts ;
INFO:  vacuuming "pg_toast.pg_toast_24611"
INFO:  table "pg_toast_24611": found 0 removable, 0 nonremovable row versions in 0 out of 0 pages
DETAIL:  0 dead row versions cannot be removed yet, oldest xmin: 773
Skipped 0 pages due to buffer pins, 0 frozen pages.
CPU: user: 0.00 s, system: 0.00 s, elapsed: 0.00 s.
INFO:  analyzing "public.pgbench_accounts"
INFO:  "pgbench_accounts": scanned 30000 of 1666667 pages, containing 1799999 live rows and 1 dead rows; 30000 rows in sample, 99999964 estimated total rows
VACUUM
postgres=#
```

**Comment by ioxgrey** [comment] 2022-03-27 08:45
I will try to go deep with optimizer statistic using https://postgrespro.com/blog/pgsql/5969296
At the moment optimizer estimates look curious.
```postgres=# explain analyze select * from pgbench_accounts where aid < 1000;
                                                          QUERY PLAN                                     
                     
---------------------------------------------------------------------------------------------------------
---------------------
 Custom Scan (o_scan) on pgbench_accounts  (cost=0.18..685.63 rows=563 width=97) (actual time=0.039..0.29
5 rows=1999 loops=1)
   Forward index scan of: pgbench_accounts_pkey
   Conds: (aid < 1000)
 Planning Time: 0.137 ms
 Execution Time: 0.353 ms
(5 rows)

postgres=# explain analyze select * from pgbench_accounts where aid < 10000;
                                                          QUERY PLAN                                     
                      
---------------------------------------------------------------------------------------------------------
----------------------
 Custom Scan (o_scan) on pgbench_accounts  (cost=0.18..685.63 rows=563 width=97) (actual time=0.024..2.58
7 rows=19999 loops=1)
   Forward index scan of: pgbench_accounts_pkey
   Conds: (aid < 10000)
 Planning Time: 0.115 ms
 Execution Time: 2.940 ms
(5 rows)

postgres=# explain analyze select * from pgbench_accounts where aid < 100000;
                                                           QUERY PLAN                                    
                        
---------------------------------------------------------------------------------------------------------
------------------------
 Custom Scan (o_scan) on pgbench_accounts  (cost=0.18..685.63 rows=563 width=97) (actual time=0.025..25.6
97 rows=199999 loops=1)
   Forward index scan of: pgbench_accounts_pkey
   Conds: (aid < 100000)
 Planning Time: 0.124 ms
 Execution Time: 28.842 ms
(5 rows)

postgres=# 
```

**Comment by ioxgrey** [comment] 2022-03-27 09:16
Historgram bounds look strange
```
postgres=# select * from pg_stats where tablename='pgbench_accounts' AND attname = 'aid';
-[ RECORD 1 ]----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
schemaname             | public
tablename              | pgbench_accounts
attname                | aid
inherited              | f
null_frac              | 0
avg_width              | 4
n_distinct             | -1
most_common_vals       | 
most_common_freqs      | 
histogram_bounds       | {83873177,92310501,93442434,94212834,94693174,95056802,95428337,95702039,95920272,96118318,96292693,96408783,96553381,96691389,96827369,96943004,97059648,97169654,97254087,97344388,97437870,97494828,97569968,97652381,97705482,97781924,97850255,97913131,97965519,98016179,98072318,98114560,98167341,98220481,98260187,98313225,98348434,98389251,98433123,98473687,98503087,98517117,98549940,98598187,98652051,98709018,98731592,98758870,98805445,98849485,98904204,98932258,98972486,98999871,99024899,99067022,99098219,99136144,99154023,99166814,99218953,99243996,99268005,99287031,99331960,99357734,99376485,99396963,99423138,99434684,99454953,99469414,99486411,99539249,99554477,99576965,99601926,99613227,99636244,99641844,99652546,99679699,99689739,99704860,99734982,99754968,99770081,99784533,99803478,99812334,99831979,99844783,99858914,99874117,99882904,99900503,99917860,99928374,99962638,99972120,99996780}
correlation            | -0.0004142992
most_common_elems      | 
most_common_elem_freqs | 
elem_count_histogram   | 

postgres=# 
```
I take one histogram bound value to look at optimizer esimates
```
postgres=# explain analyze select * from pgbench_accounts where aid > 93442434;
                                                                 QUERY PLAN                              
                                   
---------------------------------------------------------------------------------------------------------
-----------------------------------
 Custom Scan (o_scan) on pgbench_accounts  (cost=0.18..209088.21 rows=5515613 width=97) (actual time=0.05
1..1622.116 rows=13115133 loops=1)
   Forward index scan of: pgbench_accounts_pkey
   Conds: (aid > 93442434)
 Planning Time: 0.208 ms
 Execution Time: 1825.592 ms
(5 rows)

postgres=# 
```
Estimate rows looks reasonable, but explain actual rows twice more then real rows at output
```
postgres=#  select * from pgbench_accounts where aid > 93442434;

(6557566 rows)
```

**Comment by ioxgrey** [comment] 2022-03-27 09:35
An ordinary table variant looks normal. Fully correlated and all visible.  Histogram bounds are a little bit uneven, but spreaded along all the aid diapason.
```
postgres=# select * from pg_stats where tablename='pgbench_accounts' AND attname = 'aid';
-[ RECORD 1 ]----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
schemaname             | public
tablename              | pgbench_accounts
attname                | aid
inherited              | f
null_frac              | 0
avg_width              | 4
n_distinct             | -1
most_common_vals       | 
most_common_freqs      | 
histogram_bounds       | {13269,1070386,2107468,3132919,4092901,5071193,6202283,7179366,8083537,9239700,10196871,11122502,12047411,12946241,13924559,14757905,15749478,16681343,17782130,18843101,19790273,20917336,21945013,22982745,24078516,25074572,26035919,27031407,28219249,29181342,30191855,31302233,32318206,33306804,34217228,35172548,36210810,37133521,38114739,39064396,40069267,41114905,42089386,43063953,44145227,45062988,46123425,47117230,48123551,49198510,50181428,51158630,52122599,53151457,54113146,55191412,56063424,57032798,57987485,58988081,60143592,61164810,62161072,63096659,64065479,65227839,66188956,67344584,68282594,69184089,70200320,71212683,72193243,73148703,74035368,75062188,76107833,77051062,77951687,78924528,79744738,80767286,81833494,82912707,83899947,84736275,85825953,86863993,87925475,88848569,89883722,90900001,91820018,92873697,93753065,94780660,95809036,96756507,97777262,98671862,99976409}
correlation            | 1
most_common_elems      | 
most_common_elem_freqs | 
elem_count_histogram   | 

postgres=# SELECT reltuples, relpages, relallvisible
FROM pg_class WHERE relname ='pgbench_accounts';
-[ RECORD 1 ]-+--------
reltuples     | 1e+08
relpages      | 1639345
relallvisible | 1626321

postgres=# 
```

**Comment by akorotkov** [comment] 2022-03-27 12:27
@ioxgrey, thank you for details!
We'll investigate this further next week.

**Comment by akorotkov** [comment] 2022-03-28 07:11
Please, recheck e4c2175863.

**Comment by ioxgrey** [comment] 2022-03-28 07:53
Recheck on https://github.com/orioledb/orioledb/commit/e4c2175863f2e0a6cfaecf0630c88bd6b77c31b1
Histogram bound looks OK
```
postgres=# select * from pg_stats where tablename='pgbench_accounts' AND attname = 'aid';
-[ RECORD 1 ]----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
schemaname             | public
tablename              | pgbench_accounts
attname                | aid
inherited              | f
null_frac              | 0
avg_width              | 4
n_distinct             | -1
most_common_vals       | 
most_common_freqs      | 
histogram_bounds       | {592,1078477,2184048,3273868,4177090,5267686,6316025,7336772,8237217,9181097,10186798,11113339,12135987,13012139,14142165,15155738,16157694,16991540,18117441,19241073,20218690,21210226,22148765,23194795,24165663,25062294,26019326,27071652,28058155,29068773,29977876,30956611,31985744,32961246,33927481,35046336,36024005,36818784,37829043,38893471,39856810,40874891,42049680,42975295,44020170,45030967,46030217,47110154,48120642,49173147,50103107,51113802,52087295,53111100,54153619,55085104,56092636,57085653,57950864,58851386,59955816,61077495,62010429,62832769,63948871,64902743,65901779,66872208,67907848,68977586,69945952,70978130,71977715,73081944,74133711,75154606,76111278,77100016,78057398,79031243,80190154,81310131,82227034,83252198,84216027,85213470,86101390,87071956,88024272,89088738,90046732,91158783,92151648,93234526,94128556,95227366,96196627,97095927,98107221,99037904,99997968}
correlation            | -0.0062750345
most_common_elems      | 
most_common_elem_freqs | 
elem_count_histogram   | 

postgres=# 
```
Actual rows for SeqScan node OK
```
postgres=# explain analyze select count(1) from pgbench_accounts;
                                                              QUERY PLAN                                 
                              
---------------------------------------------------------------------------------------------------------
------------------------------
 Aggregate  (cost=164155.21..164155.22 rows=1 width=8) (actual time=25245.758..25245.759 rows=1 loops=1)
   ->  Seq Scan on pgbench_accounts  (cost=0.00..150084.77 rows=5628177 width=0) (actual time=0.031..2086
7.645 rows=100000000 loops=1)
 Planning Time: 0.176 ms
 Execution Time: 25245.795 ms
(4 rows)

postgres=# 
```
Estimated rows and actual rows from Custom Scan (o_scan) are wrong
```
postgres=# explain analyze select count(1) from pgbench_accounts where aid < 1000;
                                                            QUERY PLAN                                   
                          
---------------------------------------------------------------------------------------------------------
--------------------------
 Aggregate  (cost=687.02..687.03 rows=1 width=8) (actual time=0.369..0.370 rows=1 loops=1)
   ->  Custom Scan (o_scan) on pgbench_accounts  (cost=0.18..685.61 rows=563 width=0) (actual time=0.032.
.0.312 rows=1999 loops=1)
         Forward index only scan of: pgbench_accounts_pkey
         Conds: (aid < 1000)
 Planning Time: 0.140 ms
 Execution Time: 0.398 ms
(6 rows)

postgres=# explain analyze select count(1) from pgbench_accounts where aid < 10000;
                                                             QUERY PLAN                                  
                           
---------------------------------------------------------------------------------------------------------
---------------------------
 Aggregate  (cost=687.02..687.03 rows=1 width=8) (actual time=2.829..2.831 rows=1 loops=1)
   ->  Custom Scan (o_scan) on pgbench_accounts  (cost=0.18..685.61 rows=563 width=0) (actual time=0.031.
.2.444 rows=19999 loops=1)
         Forward index only scan of: pgbench_accounts_pkey
         Conds: (aid < 10000)
 Planning Time: 0.158 ms
 Execution Time: 2.863 ms
(6 rows)

postgres=#
```

**Comment by akorotkov** [comment] 2022-03-28 09:32
Hi, @ioxgrey!
The number is actual rows in Custom Scan is not true. We'll fix this.

I can't reproduce wrong number of estimated rows in Seq Scan here
```
postgres=# explain analyze select count(1) from pgbench_accounts;
                                                              QUERY PLAN                                 
                              
---------------------------------------------------------------------------------------------------------
------------------------------
 Aggregate  (cost=164155.21..164155.22 rows=1 width=8) (actual time=25245.758..25245.759 rows=1 loops=1)
   ->  Seq Scan on pgbench_accounts  (cost=0.00..150084.77 rows=*5628177* width=0) (actual time=0.031..2086
7.645 rows=100000000 loops=1)
 Planning Time: 0.176 ms
 Execution Time: 25245.795 ms
(4 rows)
```

Could you please provide a full instructing starting from initdb?

Wrong estimates in Custom Scan (o_scan) seems to be derived from wrong estimate of total rows in the table.  Both queries you provide, selects the small part of the table.  Both estimated as 0.001 of 5628177 total rows.  The question is why total number of rows is estimated as 5628177.  Full reproduction instruction could help.

Thank you!

**Comment by ioxgrey** [comment] 2022-03-28 11:21
I will rechek it next with tables created like https://github.com/orioledb/orioledb/issues/18#issuecomment-1074890566 

A standard way now get some strange result. Estimates now are OK, but the results are all-zero.
Data size looks reasonable
```du -hs `ls`| grep oriole
13G	orioledb_data
52K	orioledb_undo
```
Reproducable steps below:

```initdb -k
The files belonging to this database system will be owned by user "nikor".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.UTF-8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are enabled.

fixing permissions on existing directory /db/14 ... ok
creating subdirectories ... ok
selecting dynamic shared memory implementation ... posix
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting default time zone ... Europe/Moscow
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... ok
syncing data to disk ... ok

initdb: warning: enabling "trust" authentication for local connections
You can change this by editing pg_hba.conf or using the option -A, or
--auth-local and --auth-host, the next time you run initdb.

Success. You can now start the database server using:

    pg_ctl -D /db/14 -l logfile start

```
```cp postgresql.auto.conf /db/14/
```
```pg_ctl start
waiting for server to start............................................................... stopped waiting
pg_ctl: server did not start in time
2022-03-28 14:01:24.301 MSK [48717] LOG:  OrioleDB public alpha 4 started
2022-03-28 14:01:24.302 MSK [48717] LOG:  redirecting log output to logging collector process
2022-03-28 14:01:24.302 MSK [48717] HINT:  Future log output will appear in directory "log".
```
```
psql -d postgres
psql (14.2)
Type "help" for help.

postgres=# create extension orioledb;
CREATE EXTENSION
postgres=# \q
```
```
pgbench -i -s 1000 postgres
dropping old tables...
NOTICE:  table "pgbench_accounts" does not exist, skipping
NOTICE:  table "pgbench_branches" does not exist, skipping
NOTICE:  table "pgbench_history" does not exist, skipping
NOTICE:  table "pgbench_tellers" does not exist, skipping
creating tables...
generating data (client-side)...
100000000 of 100000000 tuples (100%) done (elapsed 254.15 s, remaining 0.00 s)
vacuuming...
creating primary keys...
done in 521.90 s (drop tables 0.00 s, create tables 0.03 s, client-side generate 254.58 s, vacuum 0.23 s, primary keys 267.06 s).
```
```psql -d postgres
psql (14.2)
Type "help" for help.

postgres=# explain analyze select count(1) from pgbench_accounts;
                                                          QUERY PLAN                                     
                     
---------------------------------------------------------------------------------------------------------
---------------------
 Aggregate  (cost=1250001.00..1250001.01 rows=1 width=8) (actual time=0.064..0.068 rows=1 loops=1)
   ->  Seq Scan on pgbench_accounts  (cost=0.00..1000001.00 rows=100000000 width=0) (actual time=0.061..0
.065 rows=0 loops=1)
 Planning Time: 0.459 ms
 Execution Time: 0.152 ms
(4 rows)

postgres=# select count(1) from pgbench_accounts;
 count 
-------
     0
(1 row)

postgres=# select count(*) from pgbench_accounts;
 count 
-------
     0
(1 row)

postgres=# select count(*) from pgbench_accounts where aid < 1000000;
 count 
-------
     0
(1 row)

```
I will recheck it with custom-created-before-data-generation pgbench tables

**Comment by akorotkov** [comment] 2022-03-28 11:38
@ioxgrey, looks strange.  Could you show your `postgresql.conf`?

**Comment by ioxgrey** [comment] 2022-03-28 11:48
All non-default values 
```cat postgresql.auto.conf 
# Do not edit this file manually!
# It will be overwritten by the ALTER SYSTEM command.
shared_buffers = '64GB'
temp_buffers = '4GB'
work_mem = '1GB'
maintenance_work_mem = '1GB'
effective_io_concurrency = '16'
max_wal_size = '4GB'
random_page_cost = '1.2'
shared_preload_libraries = '"orioledb.so"'
orioledb.main_buffers = '64GB'
orioledb.free_tree_buffers = '1GB'
orioledb.checkpoint_completion_ratio = '0.5'
orioledb.max_io_concurrency = '64'
orioledb.bgwriter_num_workers = '2'
checkpoint_timeout = '1min'
orioledb.undo_buffers = '4GB'
default_table_access_method = 'orioledb'
synchronous_commit = 'off'
max_connections = '512'
huge_pages = 'on'
huge_page_size = '1GB'
# Raw device controls
#orioledb.device_filename = '/dev/sdb1'
#orioledb.device_length = '512GB'
# Log controls
log_destination = 'stderr'
logging_collector = 'on'
```

**Comment by ioxgrey** [comment] 2022-03-28 12:33
This is  previous case with wrong estimates and right results reproduction:
```
rm -rf /db/14
rm: cannot remove '/db/14': Permission denied
``` The error above is about parent directory (/db) ownership. 
```initdb -k
The files belonging to this database system will be owned by user "nikor".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.UTF-8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are enabled.

fixing permissions on existing directory /db/14 ... ok
creating subdirectories ... ok
selecting dynamic shared memory implementation ... posix
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting default time zone ... Europe/Moscow
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... ok
syncing data to disk ... ok

initdb: warning: enabling "trust" authentication for local connections
You can change this by editing pg_hba.conf or using the option -A, or
--auth-local and --auth-host, the next time you run initdb.

Success. You can now start the database server using:

    pg_ctl -D /db/14 -l logfile start

```
```cp test/orioledb/postgresql.auto.conf /db/14
```
```pg_ctl start
waiting for server to start............................................................... stopped waiting
pg_ctl: server did not start in time
2022-03-28 15:16:33.026 MSK [48934] LOG:  OrioleDB public alpha 4 started
2022-03-28 15:16:33.027 MSK [48934] LOG:  redirecting log output to logging collector process
2022-03-28 15:16:33.027 MSK [48934] HINT:  Future log output will appear in directory "log".
```
```psql -d postgres
psql (14.2)
Type "help" for help.

postgres=# create extension orioledb;
CREATE EXTENSION
postgres=# 
\q
```
```
cat test.sql
CREATE TABLE public.pgbench_accounts (
    aid integer NOT NULL,
    bid integer,
    abalance integer,
    filler character(84),
    PRIMARY KEY (aid)
)
USING orioledb;
-- WITH (compress=10);

CREATE TABLE public.pgbench_branches (
    bid integer NOT NULL,
    bbalance integer,
    filler character(88),
    PRIMARY KEY (bid)
)
USING orioledb;
-- WITH (compress=10);

CREATE TABLE public.pgbench_history (
    tid integer,
    bid integer,
    aid integer,
    delta integer,
    mtime timestamp without time zone,
    filler character(22),
    PRIMARY KEY (bid, mtime,tid,aid,delta)
)
USING orioledb;
-- WITH (compress=10);

CREATE TABLE public.pgbench_tellers (
    tid integer NOT NULL,
    bid integer,
    tbalance integer,
    filler character(84),
    PRIMARY KEY (tid)
)
USING orioledb;
-- WITH (compress=10);


```
```
psql -d postgres < test.sql 
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
```
```pgbench -i -I gv -s 1000 postgres
generating data (client-side)...
100000000 of 100000000 tuples (100%) done (elapsed 235.99 s, remaining 0.00 s)
vacuuming...
done in 236.67 s (client-side generate 236.45 s, vacuum 0.22 s).
```
```psql -d postgres
psql (14.2)
Type "help" for help.

postgres=# explain analyze select count(1) from pgbench_accounts;
                                                              QUERY PLAN                                 
                              
---------------------------------------------------------------------------------------------------------
------------------------------
 Aggregate  (cost=164155.21..164155.22 rows=1 width=8) (actual time=24674.038..24674.059 rows=1 loops=1)
   ->  Seq Scan on pgbench_accounts  (cost=0.00..150084.77 rows=5628177 width=0) (actual time=0.068..2061
8.708 rows=100000000 loops=1)
 Planning Time: 0.397 ms
 Execution Time: 24674.239 ms
(4 rows)

postgres=# explain analyze select count(1) from pgbench_accounts where aid < 1000000;
                                                                 QUERY PLAN                              
                                   
---------------------------------------------------------------------------------------------------------
-----------------------------------
 Aggregate  (cost=58448.55..58448.56 rows=1 width=8) (actual time=340.895..340.897 rows=1 loops=1)
   ->  Custom Scan (o_scan) on pgbench_accounts  (cost=0.18..58288.91 rows=63858 width=0) (actual time=0.
091..282.976 rows=1999999 loops=1)
         Forward index only scan of: pgbench_accounts_pkey
         Conds: (aid < 1000000)
 Planning Time: 0.294 ms
 Execution Time: 340.992 ms
(6 rows)

postgres=# 
```

**Comment by akorotkov** [comment] 2022-03-29 12:30
@ioxgrey, could you re-check the empty table problem on 1a8bfef87f?

**Comment by ioxgrey** [comment] 2022-03-29 14:32
Results are OK.
Optimizer estimations are wrong
```
postgres=# explain analyze select count(1) from pgbench_accounts;
                                                              QUERY PLAN                                 
                              
---------------------------------------------------------------------------------------------------------
------------------------------
 Aggregate  (cost=98898.40..98898.41 rows=1 width=8) (actual time=17539.130..17539.141 rows=1 loops=1)
   ->  Seq Scan on pgbench_accounts  (cost=0.00..92414.92 rows=2593392 width=0) (actual time=59.673..1354
2.328 rows=100000000 loops=1)
 Planning Time: 0.354 ms
 Execution Time: 17541.031 ms
(4 rows)

postgres=# select count(1) from pgbench_accounts;
   count   
-----------
 100000000
(1 row)

postgres=# explain analyze select count(1) from pgbench_accounts where aid < 1000000;
                                                                 QUERY PLAN                              
                                   
---------------------------------------------------------------------------------------------------------
-----------------------------------
 Aggregate  (cost=28519.82..28519.83 rows=1 width=8) (actual time=306.427..306.429 rows=1 loops=1)
   ->  Custom Scan (o_scan) on pgbench_accounts  (cost=0.18..28449.21 rows=28242 width=0) (actual time=0.
048..265.852 rows=1999999 loops=1)
         Forward index only scan of: pgbench_accounts_pkey
         Conds: (aid < 1000000)
 Planning Time: 0.126 ms
 Execution Time: 306.476 ms
(6 rows)

postgres=# 
```
BTW, can you add commit hash number to start message like this?
```
2022-03-29 17:18:40.442 MSK [61463] LOG:  OrioleDB public alpha 4 started
```

**Comment by akorotkov** [comment] 2022-03-30 13:54
Please, recheck 09ad7a52cc.

> BTW, can you add commit hash number to start message like this?
> 
> ```
> 2022-03-29 17:18:40.442 MSK [61463] LOG:  OrioleDB public alpha 4 started
> ```

Will do this a bit later.

**Comment by ioxgrey** [comment] 2022-03-30 14:28
Excelent! Full table scan and partial index scan estimations looks reasonable. Results rows counts are precise.
```
postgres=# explain analyze select count(1) from pgbench_accounts;
                                                               QUERY PLAN                                
                                
---------------------------------------------------------------------------------------------------------
--------------------------------
 Aggregate  (cost=2916666.60..2916666.61 rows=1 width=8) (actual time=25669.214..25669.216 rows=1 loops=1
)
   ->  Seq Scan on pgbench_accounts  (cost=0.00..2666666.68 rows=99999968 width=0) (actual time=0.067..20
650.030 rows=100000000 loops=1)
 Planning Time: 0.386 ms
 Execution Time: 25669.303 ms
(4 rows)

postgres=# explain analyze select count(1) from pgbench_accounts where aid < 1000000;
                                                                  QUERY PLAN                             
                                      
---------------------------------------------------------------------------------------------------------
--------------------------------------
 Aggregate  (cost=1079199.80..1079199.81 rows=1 width=8) (actual time=299.529..299.531 rows=1 loops=1)
   ->  Custom Scan (o_scan) on pgbench_accounts  (cost=0.19..1076345.86 rows=1141575 width=0) (actual tim
e=0.122..255.623 rows=999999 loops=1)
         Forward index only scan of: pgbench_accounts_pkey
         Conds: (aid < 1000000)
 Planning Time: 0.127 ms
 Execution Time: 299.583 ms
(6 rows)

postgres=# explain analyze select count(1) from pgbench_accounts where aid < 10000;
                                                              QUERY PLAN                                 
                              
---------------------------------------------------------------------------------------------------------
------------------------------
 Aggregate  (cost=12166.37..12166.38 rows=1 width=8) (actual time=3.048..3.049 rows=1 loops=1)
   ->  Custom Scan (o_scan) on pgbench_accounts  (cost=0.19..12141.37 rows=10000 width=0) (actual time=0.
024..2.607 rows=9999 loops=1)
         Forward index only scan of: pgbench_accounts_pkey
         Conds: (aid < 10000)
 Planning Time: 0.138 ms
 Execution Time: 3.073 ms
(6 rows)

postgres=# 
```

**Comment by akorotkov** [comment] 2022-04-14 21:44
The fix is released in alpha6.
@ioxgrey, thank you for your efforts on reporting problems and keeping in touch!

**Closed by akorotkov** 2022-04-14 21:44 UTC
