### ISSUE TITLE
Assert: PreCommit_CheckForSerializationFailure: !SxactIsPartiallyReleased(MySerializableXact)

### ISSUE THREAD

**Issue by Tanyaevm** [orioledb/orioledb#93] opened 2022-10-06 15:39 UTC
specs/test.spec:

```sql
setup
{
	CREATE EXTENSION IF NOT EXISTS orioledb;

	CREATE TABLE o_test_1 USING orioledb 
		AS SELECT generate_series(1, 10)::int a;

	ALTER TABLE o_test_1 SET (parallel_workers = 2);
}

teardown
{
	DROP TABLE o_test_1;
}

session s1
setup 		{ BEGIN TRANSACTION ISOLATION LEVEL SERIALIZABLE; }

step select_1	{ SELECT * FROM o_test_1; }
step commit_1 	{ COMMIT; }

session s2
setup		{
			  BEGIN TRANSACTION ISOLATION LEVEL SERIALIZABLE READ ONLY;
			  SET parallel_setup_cost = 0;
			  SET parallel_tuple_cost = 0;
			}

step select_2_1	{ SELECT * FROM o_test_1; }
step select_2_2	{ SELECT * FROM o_test_1; }
step commit_2	{ COMMIT; }

permutation select_1 select_2_1 commit_1 select_2_2 commit_2
```

Coredump
```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007fcb693c0859 in __GI_abort () at abort.c:79
#2  0x000055cb318df188 in ExceptionalCondition (conditionName=conditionName@entry=0x55cb31a76c28 "!SxactIsPartiallyReleased(MySerializableXact)", errorType=errorType@entry=0x55cb3193c00b "FailedAssertion", fileName=fileName@entry=0x55cb31a75b1f "predicate.c", lineNumber=lineNumber@entry=4847) at assert.c:69
#3  0x000055cb317a0c0e in PreCommit_CheckForSerializationFailure () at predicate.c:4847
#4  0x000055cb314f246d in CommitTransaction () at xact.c:2239
#5  0x000055cb314f3865 in CommitTransactionCommand () at xact.c:3196
#6  0x000055cb317aa019 in finish_xact_command () at postgres.c:2734
#7  0x000055cb317ac52b in finish_xact_command () at postgres.c:2732
#8  exec_simple_query (query_string=0x55cb32fc24b0 "COMMIT;") at postgres.c:1275
#9  0x000055cb317adfce in PostgresMain (dbname=<optimized out>, username=<optimized out>) at postgres.c:4544
#10 0x000055cb3171525a in BackendRun (port=<optimized out>, port=<optimized out>) at postmaster.c:4510
#11 BackendStartup (port=<optimized out>) at postmaster.c:4238
#12 ServerLoop () at postmaster.c:1812
#13 0x000055cb317163cb in PostmasterMain (argc=<optimized out>, argv=0x55cb32fbcc30) at postmaster.c:1484
#14 0x000055cb314376a0 in main (argc=8, argv=0x55cb32fbcc30) at main.c:202
```

Run as:
```
make USE_PGXS=1 isolationcheck ISOLATIONCHECKS="test"
```

**Comment by akorotkov** [comment] 2022-12-29 06:16
Duplicate of #131

**Closed by akorotkov** 2022-12-29 06:16 UTC
Labels: bug
