### ISSUE TITLE
Test stuck with using orioledb

### ISSUE THREAD

**Issue by Tanyaevm** [orioledb/orioledb#96] opened 2022-10-10 12:45 UTC
specs/test.spec:

Error for postgres:
```
ERROR:  could not serialize access due to read/write dependencies among transactions
```

Test stuck with using orioledb:

```sql
setup
{
	CREATE EXTENSION IF NOT EXISTS orioledb;

	CREATE TABLE o_test_1 (
		val_1 TEXT PRIMARY KEY, 
		val_2 DECIMAL NOT NULL
	)USING orioledb;
	
	INSERT INTO o_test_1 (val_1, val_2) 
		VALUES ('X', 0), ('Y', 0);
}

teardown
{
	DROP TABLE o_test_1;
}

session s1
setup 		{ BEGIN TRANSACTION ISOLATION LEVEL SERIALIZABLE; }
step "select_1"	{ SELECT val_2 FROM o_test_1 WHERE val_1 = 'Y'; }
step "update_1"	{ UPDATE o_test_1 SET val_2 = 20 WHERE val_1 = 'Y'; }
step "commit_1" { COMMIT; }

session s2
setup		{ BEGIN TRANSACTION ISOLATION LEVEL SERIALIZABLE; }
step "select_2_1"	{ SELECT val_2 FROM o_test_1 WHERE val_1 = 'X'; }
step "select_2_2"	{ SELECT val_2 FROM o_test_1 WHERE val_1 = 'Y'; }
step "update_2"	{ UPDATE o_test_1 SET val_2 = -11 WHERE val_1 = 'X'; }

session s3
setup		{ BEGIN TRANSACTION ISOLATION LEVEL SERIALIZABLE; }
step "select_3"	{ SELECT val_1, val_2 FROM o_test_1 
					WHERE val_1 IN ('X', 'Y') ORDER BY val_1; }
step "commit_3"	{ COMMIT; }

permutation "select_2_1" "select_2_2" "select_1" "update_1" "commit_1" "select_3" "commit_3" "update_2"
```

Run as:
```
make USE_PGXS=1 isolationcheck ISOLATIONCHECKS="test"
```

**Comment by akorotkov** [comment] 2022-12-29 06:19
Duplicate of #131

**Closed by akorotkov** 2022-12-29 06:19 UTC
Labels: bug
