### ISSUE TITLE
Test stuck with using orioledb

### ISSUE THREAD

**Issue by Tanyaevm** [orioledb/orioledb#43] opened 2022-09-29 09:18 UTC
sql/test.sql:

```sql
CREATE EXTENSION IF NOT EXISTS orioledb;

CREATE TABLE o_test_1 (val_1 VARCHAR(10))USING orioledb;
INSERT INTO o_test_1 VALUES ('a');

BEGIN TRANSACTION ISOLATION LEVEL SERIALIZABLE;
INSERT INTO o_test_1 VALUES ('d');
PREPARE TRANSACTION 't1';
COMMIT PREPARED 't1';

BEGIN TRANSACTION ISOLATION LEVEL SERIALIZABLE;
UPDATE o_test_1 SET val_1 = 'e';
PREPARE TRANSACTION 't2';

BEGIN TRANSACTION ISOLATION LEVEL SERIALIZABLE;
SELECT * FROM o_test_1;
INSERT INTO o_test_1 VALUES ('f');
PREPARE TRANSACTION 't3';
ROLLBACK PREPARED 't2';

DROP TABLE o_test_1;
```

Error for postgres:
```
ERROR:  could not serialize access due to read/write dependencies among transactions
DETAIL:  Reason code: Canceled on identification as a pivot, during write.
HINT:  The transaction might succeed if retried.
```

Run as:
```
make regresscheck USE_PGXS=1 REGRESSCHECKS="test"
```

**Comment by akorotkov** [comment] 2022-12-29 06:23
Duplicate of #131

**Closed by akorotkov** 2022-12-29 06:23 UTC
Labels: bug
