### ISSUE TITLE
Error message is different:  duplicate key value violates unique constraint "o_test_1_pkey"

### ISSUE THREAD

**Issue by Tanyaevm** [orioledb/orioledb#130] opened 2022-12-28 11:44 UTC
specs/test.spec:

Error with postgres:

```
ERROR:  duplicate key value violates unique constraint "o_test_1_pkey"
```

Error with orioledb:

```
ERROR:  could not serialize access due to concurrent update
```

```sql
setup
{
    CREATE EXTENSION IF NOT EXISTS orioledb;
    
    CREATE TABLE o_test_1(
        val_1 int,
        val_2 int,
        PRIMARY KEY (val_1, val_2)
    )USING orioledb;

    INSERT INTO o_test_1 VALUES (5, 1), (5, 2);
}

teardown
{
    DROP TABLE o_test_1;
}

session "s1"

setup { BEGIN ISOLATION LEVEL SERIALIZABLE; }

step "select_1" { SELECT * FROM o_test_1 WHERE val_1 = 5; }
step "insert_1" { INSERT INTO o_test_1 VALUES (5, 3); }
step "commit_1" { COMMIT; }

session "s2"

setup { BEGIN ISOLATION LEVEL SERIALIZABLE; }

step "insert_2" { INSERT INTO o_test_1 VALUES (5, 3); }
step "commit_2" { COMMIT; }

permutation "select_1" "insert_1" "insert_2" "commit_1" "commit_2"
```

Run as:
```
make USE_PGXS=1 isolationcheck ISOLATIONCHECKS="test"
```

**Comment by akorotkov** [comment] 2022-12-29 06:21
Duplicate of #131

**Closed by akorotkov** 2022-12-29 06:21 UTC
Labels: bug
