### ISSUE TITLE
NO ERROR:  could not serialize access due to read/write dependencies among transactions

### ISSUE THREAD

**Issue by Tanyaevm** [orioledb/orioledb#90] opened 2022-10-03 12:43 UTC
sql/test.sql:

**Error with orioledb:** test stuck
```sql
CREATE TABLE o_test_1 (val_1 VARCHAR(10))USING orioledb;

INSERT INTO o_test_1 VALUES ('aaa');

SELECT gid FROM pg_prepared_xacts;

BEGIN TRANSACTION ISOLATION LEVEL SERIALIZABLE;
INSERT INTO o_test_1 VALUES ('ddd');

PREPARE TRANSACTION 'foo2';

COMMIT PREPARED 'foo2';

BEGIN TRANSACTION ISOLATION LEVEL SERIALIZABLE;

UPDATE o_test_1 SET val_1 = 'eee' WHERE val_1 = 'ddd';

PREPARE TRANSACTION 'foo4';

SELECT gid FROM pg_prepared_xacts;

BEGIN TRANSACTION ISOLATION LEVEL SERIALIZABLE;
SELECT * FROM o_test_1;

INSERT INTO o_test_1 VALUES ('fff');
PREPARE TRANSACTION 'foo5';

SELECT gid FROM pg_prepared_xacts;

ROLLBACK PREPARED 'foo4';

SELECT gid FROM pg_prepared_xacts;

DROP TABLE o_test_1;
```

**Error for postgres:**
```sql
CREATE TABLE o_test_1 (val_1 VARCHAR(10));--USING orioledb;

INSERT INTO o_test_1 VALUES ('aaa');

SELECT gid FROM pg_prepared_xacts;

BEGIN TRANSACTION ISOLATION LEVEL SERIALIZABLE;
INSERT INTO o_test_1 VALUES ('ddd');

PREPARE TRANSACTION 'foo2';

COMMIT PREPARED 'foo2';

BEGIN TRANSACTION ISOLATION LEVEL SERIALIZABLE;

UPDATE o_test_1 SET val_1 = 'eee' WHERE val_1 = 'ddd';

PREPARE TRANSACTION 'foo4';

SELECT gid FROM pg_prepared_xacts;

BEGIN TRANSACTION ISOLATION LEVEL SERIALIZABLE;
SELECT * FROM o_test_1;

INSERT INTO o_test_1 VALUES ('fff');

--ERROR:  could not serialize access due to read/write dependencies among transactions
--DETAIL:  Reason code: Canceled on identification as a pivot, during write.
--HINT:  The transaction might succeed if retried.

PREPARE TRANSACTION 'foo5';

SELECT gid FROM pg_prepared_xacts;

ROLLBACK PREPARED 'foo4';

SELECT gid FROM pg_prepared_xacts;

DROP TABLE o_test_1;
```

Run as:
```
make regresscheck USE_PGXS=1 REGRESSCHECKS="test"
```

**Comment by akorotkov** [comment] 2022-12-29 06:16
Duplicate of #131

**Closed by akorotkov** 2022-12-29 06:16 UTC
Labels: bug
