### ISSUE TITLE
Why is Table Inheritance Not Supported

### ISSUE THREAD

**Issue by JoshInnis** [orioledb/orioledb#103] opened 2022-10-18 23:47 UTC
I have a system that relies heavily on Table Inheritance. I am interested in using orioledb, but orioledb  currently doesn't support this feature. Is there a reason orioledb can't support it, or is that something planned to be added?

**Comment by akorotkov** [comment] 2022-10-19 18:30
Hi, @JoshInnis!
Thank you for your report.
OrioleDB have no intention to miss inheritance.  It works at least in some basic cases that we cover with regression tests.
You must have spotted a bug.  Could  you please share a full reproduction script for your case, when inheritance doesn't work properly?

**Comment by emotionbug** [comment] 2022-10-21 06:59
Looks working on this branch. :)
Previously, "INHERITS" throw error with message "ERROR: INHERITS is not supported for orioledb tables.".
https://github.com/orioledb/orioledb/tree/inherits_support

**Comment by homper** [comment] 2022-10-21 08:26
Yes, we understood that we made a mistake saying that it works and reenabled it and fixed support of basic cases; but some might not work yet because they are not tested, like multiple parents, deep inheritance trees and something else
Will be tested and fixed on [inherits_support](https://github.com/orioledb/orioledb/tree/inherits_support) branch soon.

**Comment by JoshInnis** [comment] 2022-10-26 04:32
Awesome, thanks for the quick update.

**Comment by homper** [comment] 2022-11-30 16:37
Fix merged to [main](https://github.com/orioledb/orioledb)

**Closed by homper** 2022-11-30 16:37 UTC
