### ISSUE TITLE
Error message is different

### ISSUE THREAD

**Issue by Tanyaevm** [orioledb/orioledb#94] opened 2022-10-10 10:15 UTC
specs/test.spec:

Error for postgres:
```
ERROR:  could not serialize access due to read/write dependencies among transactions
```

Error with orioledb:
```
ERROR:  could not serialize access due to concurrent update
```

```sql
setup
{
CREATE EXTENSION IF NOT EXISTS orioledb;
CREATE TABLE o_test_1 (
      val_1 integer PRIMARY KEY
)USING orioledb;
}

teardown
{
  DROP TABLE o_test_1;
}

session s1
setup { BEGIN ISOLATION LEVEL SERIALIZABLE; }
step "select_1" { SELECT * FROM o_test_1; }
step "insert_1" { INSERT INTO o_test_1 VALUES (42); }
step "commit_1" { COMMIT; }

session s2
setup { BEGIN ISOLATION LEVEL SERIALIZABLE; }
step "select_2" { SELECT * FROM o_test_1; }
step "insert_2" { INSERT INTO o_test_1 VALUES (42); }
step "commit_2" { COMMIT; }

permutation "select_1" "select_2" "insert_1" "insert_2" "commit_1" "commit_2"
```

Run as:
```
make USE_PGXS=1 isolationcheck ISOLATIONCHECKS="test"
```

**Comment by akorotkov** [comment] 2022-12-27 23:53
Need to explicitly forbid OrioleDB with Serializable, because it's not yet implemented.

**Comment by akorotkov** [comment] 2022-12-29 06:20
Duplicate of #131

**Closed by akorotkov** 2022-12-29 06:20 UTC
Labels: bug
